CREATE DATABASE SSB;

USE SSB;

CREATE TABLE SSB.CUSTOMER ( 
C_CUSTKEY     INT,
C_NAME        string,
C_ADDRESS     string,
C_CITY        string,
C_NATION      string,
C_REGION      string,
C_PHONE       string,
C_MKTSEGMENT   string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/user/root/ssb/data/customer';

CREATE TABLE SSB.DATES ( 
D_DATEKEY          INT,
D_DATE             string,
D_DAYOFWEEK        string,
D_MONTH            string,
D_YEAR             INT,
D_YEARMONTHNUM     INT,
D_YEARMONTH        string,
D_DAYNUMINWEEK     INT,
D_DAYNUMINMONTH    INT,
D_DAYNUMINYEAR     INT,
D_MONTHNUMINYEAR   INT,
D_WEEKNUMINYEAR    INT,
D_SELLINGSEASON    string,
D_LASTDAYINWEEKFL  INT,
D_LASTDAYINMONTHFL INT,
D_HOLIDAYFL        INT,
D_WEEKDAYFL        INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/user/root/ssb/data/date';
              
CREATE TABLE SSB.PART ( 
P_PARTKEY     INT,
P_NAME        string,
P_MFGR        string,
P_CATEGORY    string,
P_BRAND       string,
P_COLOR       string,
P_TYPE        string,
P_SIZE        INT,
P_CONTAINER   string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/user/root/ssb/data/part';

CREATE TABLE SSB.SUPPLIER ( 
S_SUPPKEY     INT,
S_NAME        string,
S_ADDRESS     string,
S_CITY        string,
S_NATION      string,
S_REGION      string,
S_PHONE       string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/user/root/ssb/data/supplier';

CREATE TABLE SSB.LINEORDER ( 
LO_ORDERKEY       BIGINT,
LO_LINENUMBER     BIGINT,
LO_CUSTKEY        INT,
LO_PARTKEY        INT,
LO_SUPPKEY        INT,
LO_ORDERDATE      INT,
LO_ORDERPRIOTITY  string,
LO_SHIPPRIOTITY   INT,
LO_QUANTITY       BIGINT,
LO_EXTENDEDPRICE  BIGINT,
LO_ORDTOTALPRICE  BIGINT,
LO_DISCOUNT       BIGINT,
LO_REVENUE        BIGINT,
LO_SUPPLYCOST     BIGINT,
LO_TAX            BIGINT,
LO_COMMITDATE     INT,
LO_SHIPMODE       string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/user/root/ssb/data/lineorder';
