USE <DATABASE>;

CREATE VIEW P_LINEORDER AS
SELECT LO_ORDERKEY,     
LO_LINENUMBER,
LO_CUSTKEY,  
LO_PARTKEY,     
LO_SUPPKEY,
LO_ORDERDATE,
LO_ORDERPRIOTITY,
LO_SHIPPRIOTITY, 
LO_QUANTITY,     
LO_EXTENDEDPRICE,
LO_ORDTOTALPRICE,
LO_DISCOUNT,     
LO_REVENUE,      
LO_SUPPLYCOST,   
LO_TAX,          
LO_COMMITDATE,   
LO_SHIPMODE,
LO_EXTENDEDPRICE*LO_DISCOUNT AS V_REVENUE
FROM <DATABASE>.LINEORDER;
