USE <DATABASE>;

SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.dynamic.partition=true;
SET hive.exec.max.dynamic.partitions=25560;
SET hive.exec.max.dynamic.partitions.pernode=25560;

CREATE TABLE <DATABASE>.P_LINEORDER (
LO_ORDERKEY       BIGINT,
LO_LINENUMBER     BIGINT,
LO_CUSTKEY        INT,
LO_PARTKEY        INT,
LO_SUPPKEY        INT,
LO_ORDERPRIOTITY  string,
LO_SHIPPRIOTITY   INT,
LO_QUANTITY       BIGINT,
LO_EXTENDEDPRICE  BIGINT,
LO_ORDTOTALPRICE  BIGINT,
LO_DISCOUNT       BIGINT,
LO_REVENUE        BIGINT,
LO_SUPPLYCOST     BIGINT,
LO_TAX            BIGINT,
LO_COMMITDATE     INT,
LO_SHIPMODE       string,
V_REVENUE         BIGINT
) PARTITIONED BY (LO_ORDERDATE INT);

INSERT INTO TABLE <DATABASE>.P_LINEORDER PARTITION(LO_ORDERDATE)
SELECT LO_ORDERKEY,     
LO_LINENUMBER,
LO_CUSTKEY,  
LO_PARTKEY,     
LO_SUPPKEY,   
LO_ORDERPRIOTITY,
LO_SHIPPRIOTITY, 
LO_QUANTITY,     
LO_EXTENDEDPRICE,
LO_ORDTOTALPRICE,
LO_DISCOUNT,     
LO_REVENUE,      
LO_SUPPLYCOST,   
LO_TAX,          
LO_COMMITDATE,   
LO_SHIPMODE,
LO_EXTENDEDPRICE * LO_DISCOUNT AS V_REVENUE,
LO_ORDERDATE
FROM <DATABASE>.LINEORDER
DISTRIBUTE BY LO_ORDERDATE;
